version: '2'
services:
    pomodoro-app:
        image: pomodoro
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://pomodoro-postgresql:5432/pomodoro
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pomodoro-postgresql:
        extends:
            file: postgresql.yml
            service: pomodoro-postgresql
